api:
  host: '127.0.0.1'
  port: 5000
  llm:
    model:
      type: "llama"
      repo: "TheBloke/Nous-Hermes-Llama2-GGUF"
      filename: "nous-hermes-llama2-13b.Q6_K.gguf"
      max_response_tokens: 1024
      n_batch: 2048
      n_ctx: 4096
      n_gpu_layers: -1
      repeat_penalty: 1.176
      temperature: 0.71
      top_k: 40
      top_p: 0.1
      verbose: True
data_dir: '/home/core/llm/chatbot/data'
workflows:
  libpages:
    name: 'libpages'
    rag:
      name: 'libpages'
      stack:
        class_name: 'RagStack'
      collectors:
        -
          name: 'Library Pages'
          class_name: 'LibPagesCollector'
          output: 'collector/libpages/data/output'
          config:
            cache_urls: True
            ignore_links: True
            images_to_alt: True
            unicode_snob: True
      context:
        size: 4096
        max_vector_distance: 1.0
      chunker:
        modulename: 'charcter_text_splitter'
        class_name: 'CharacterTextSplitterChunker'
        config:
          chunk_size: 1024
          overlap: 128
          split_on: "\n"
          add_document_metadata: False
          write_chunks_to_disk: True
      context_builder:
        class_name: 'SimpleContextAggregator'
      context_database:
        class_name: 'SQLite'
        name: 'libpages'
      embedding_database:
        class_name: 'LanceDB'
        name: 'libpages'
      embedding_encoder:
        class_name: 'SentenceTransformerEncoder'
        model: 'avsolatorio/GIST-large-Embedding-v0'
      query_processor:
        class_name: 'StandardQueryProcessor'
      reranker:
        class_name: 'SentenceTransformerEncoder'
        model: 'BAAI/bge-reranker-large'
        n_results: 5

