api:
  host: '127.0.0.1'
  port: 5000
  llm:
    model:
      type: "llama"
      repo: "TheBloke/Nous-Hermes-Llama2-GGUF"
      filename: "nous-hermes-llama2-13b.Q6_K.gguf"
      max_response_tokens: 1024
      n_batch: 2048
      n_ctx: 4096
      n_gpu_layers: -1
      repeat_penalty: 1.176
      temperature: 0.71
      top_k: 40
      top_p: 0.1
      verbose: True
data_dir: '/home/core/llm/chatbot/data'
rag:
  archiveswikipages:
    name: 'archiveswikipages'
    rag:
      name: 'archiveswikipages'
      stack:
        module_name: 'deckard.rag'
        class_name: 'RagStack'
      collectors:
        -
          name: 'Archives Wiki Pages'
          module_name: 'deckard.collectors'
          class_name: 'ArchivesHistoryCollector'
          output: 'collector/archivespages/data/output'
          config:
            host: 'localhost'
            port: '3306'
            database: 'unbhistory'
      context:
        size: 4096
        max_vector_distance: 1.0
      chunker:
        module_name: 'deckard.chunkers'
        class_name: 'CharacterTextSplitterChunker'
        config:
          chunk_size: 1024
          overlap: 128
          split_on: "\n"
          add_document_metadata: False
          write_chunks_to_disk: True
      context_builder:
        module_name: 'deckard.context_builders'
        class_name: 'SimpleContextAggregator'
      context_database:
        module_name: 'deckard.databases'
        class_name: 'SQLite'
        name: 'libpages'
      embedding_database:
        module_name: 'deckard.databases'
        class_name: 'LanceDB'
        name: 'libpages'
      embedding_encoder:
        module_name: 'deckard.encoders'
        class_name: 'SentenceTransformerEncoder'
        model: 'avsolatorio/GIST-large-Embedding-v0'
      query_processor:
        module_name: 'deckard.query_processors'
        class_name: 'StandardQueryProcessor'
      reranker:
        module_name: 'deckard.encoders'
        class_name: 'SentenceTransformerEncoder'
        model: 'BAAI/bge-reranker-large'
        max_raw_results: 10

