api:
  host: '0.0.0.0'
  port: 5000
  llm:
    model:
      type: "llama"
      repo: "NousResearch/Hermes-3-Llama-3.1-8B-GGUF"
      filename: "Hermes-3-Llama-3.1-8B.Q8_0.gguf"
      max_response_tokens: 1024
      n_batch: 2048
      n_ctx: 8192
      n_gpu_layers: -1
      repeat_penalty: 1.176
      temperature: 0.2
      top_k: 40
      top_p: 0.95
      min_p: 0.05
      verbose: True
  gpu_lock_file: 'RTX_4090_1.lock'
data_dir: '/home/core/llm/chatbot/data'
rag:
  libpages:
    name: 'libpages'
    rag:
      name: 'libpages'
      stack:
        module_name: 'deckard.rag'
        class_name: 'RagStack'
      collectors:
        -
          name: 'Library Pages'
          module_name: 'deckard.collectors'
          class_name: 'LibPagesCollector'
          output: 'collector/libpages/data/output'
          config:
            cache_urls: True
            ignore_links: True
            images_to_alt: True
            unicode_snob: True
      context:
        size: 8192
        max_vector_distance: 1.0
      chunker:
        module_name: 'deckard.chunkers'
        class_name: 'CharacterTextSplitterChunker'
        config:
          chunk_size: 1024
          overlap: 128
          split_on: "\n"
          add_document_metadata: False
          write_chunks_to_disk: True
      context_builder:
        module_name: 'deckard.context_builders'
        class_name: 'SimpleContextAggregator'
      context_database:
        module_name: 'deckard.databases'
        class_name: 'SQLite'
        name: 'libpages'
      embedding_database:
        module_name: 'deckard.databases'
        class_name: 'LanceDB'
        name: 'libpages'
      sparse_search:
          module_name: 'deckard.sparse'
          class_name: 'Solr'
          uri: 'http://localhost:3514/solr/deckard'
      embedding_encoder:
        module_name: 'deckard.encoders'
        class_name: 'SentenceTransformerEncoder'
        model: 'mixedbread-ai/mxbai-embed-large-v1'
      query_processor:
        module_name: 'deckard.query_processors'
        class_name: 'StandardQueryProcessor'
      reranker:
        module_name: 'deckard.encoders'
        class_name: 'SentenceTransformerEncoder'
        model: 'BAAI/bge-reranker-v2-m3'
        max_raw_results: 10
client:
  timeout: 600
  uri: 'http://127.0.0.1:5000/deckard/api/v1'
  user_agent: 'Deckard/0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
  pub_key: ''
  priv_key: ''
